"""din mor

Revision ID: 24b60c91c130
Revises: 76520e947564
Create Date: 2023-01-20 08:12:07.815932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b60c91c130'
down_revision = '76520e947564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kurv', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betaling', schema=None) as batch_op:
        batch_op.drop_column('kurv')

    # ### end Alembic commands ###
