"""din mor

Revision ID: 76520e947564
Revises: c63a127270a0
Create Date: 2023-01-20 07:52:52.279115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76520e947564'
down_revision = 'c63a127270a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betaling')
    # ### end Alembic commands ###
